### ISSUE TITLE
Incorrect exception handling in Python 3: ctx.ignoreExceptions

### ISSUE THREAD

**Issue by manics** [ome/omero-web#144]
This error was seen in the `OMERO.web` log of `omero.lifesci.dundee.ac.uk`:
```
2020-02-26 14:52:49,404 ERROR [                          django.request] (proc.09119) handle_uncaught_exception():135 Internal Server Error: /webgateway/render_image/3970392/
Traceback (most recent call last):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 7780, in wrapped
    if not self._prepareRenderingEngine() \
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 8056, in _prepareRenderingEngine
    self._re = self._prepareRE(rdid=rdid)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 8035, in _prepareRE
    re.load(ctx)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4746, in __call__
    return self.f(*args, **kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_api_RenderingEngine_ice.py", line 1192, in load
    return _M_omero.api.RenderingEngine._op_load.invoke(self, ((), _ctx))
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 201, in handle_abort
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 485, in wrapped
    retval = f(request, *args, **kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webgateway/views.py", line 1018, in render_image
    jpeg_data = img.renderJpeg(z, t, compression=compress_quality)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 7785, in wrapped
    except ctx.ignoreExceptions:
TypeError: catching classes that do not inherit from BaseException is not allowed
2020-02-26 14:52:49,404 ERROR [                          django.request] (proc.09119) handle_uncaught_exception():135 HTTP 500 <WSGIRequest: GET '/webgateway/render_image/3970392/'>
Traceback (most recent call last):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 7780, in wrapped
    if not self._prepareRenderingEngine() \
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 8056, in _prepareRenderingEngine
    self._re = self._prepareRE(rdid=rdid)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 8035, in _prepareRE
    re.load(ctx)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4746, in __call__
    return self.f(*args, **kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_api_RenderingEngine_ice.py", line 1192, in load
    return _M_omero.api.RenderingEngine._op_load.invoke(self, ((), _ctx))
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/gunicorn/workers/base.py", line 201, in handle_abort
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 485, in wrapped
    retval = f(request, *args, **kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webgateway/views.py", line 1018, in render_image
    jpeg_data = img.renderJpeg(z, t, compression=compress_quality)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 7785, in wrapped
    except ctx.ignoreExceptions:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

The original exception probably doesn't matter, but the failure to handle it:
`TypeError: catching classes that do not inherit from BaseException is not allowed`
is fatal to that particular worker:
`SystemExit: 1`

**Comment by sbesson** [comment]
This has been addressed via https://github.com/ome/omero-py/pull/447 and OMERO.py 5.19.7
