### ISSUE TITLE
Logging: OptimisticLockException shouldn't print the entire graph

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#166]
```
2020-04-24 13:18:58,120 WARNI [ omero.gateway] (proc.15221) debug():4728 OptimisticLockException on <class 'omeroweb.webclient.webclient_gateway.OmeroWebSafeCallWrapper'> to <8aae5714-c49e-4daf-91e1-d482c9e1abc0omero.api.IUpdate> saveAndReturnObject((object #0 (::omero::model::FileAnnotation)
{
_id = object #1 (::omero::RLong)
{
_val = 7172
... many more lines ...
```

**Comment by joshmoore** [comment]
Just seen again on demo:

```
2020-06-02 14:30:26,746 ERROR [ django.request] (proc.28959) handle_uncaught_exception():135 Internal Server Error: /webclient/annotate_rating/
...
2020-06-02 14:30:29,691 ERROR [ omeroweb.feedback.views] (proc.28959) handler500():153 handler500: Server error
2020-06-02 14:30:29,692 ERROR [ omeroweb.feedback.views] (proc.28959) handler500():156 Traceback (most recent call last):
...
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 2126, in handle_exception
e, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4746, in __call__
return self.f(*args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_api_IUpdate_ice.py", line 163, in saveAndReturnObject
return _M_omero.api.IUpdate._op_saveAndReturnObject.invoke(self, ((obj, ), _ctx))

omero.OptimisticLockException: exception ::omero::OptimisticLockException
{
serverStackTrace = ome.conditions.OptimisticLockException: You are not authorized to change the update event for ome.model.annotations.LongAnnotation:Id_7310 from ome.model.meta.Event:Id_16458536 to ome.model.meta.Event:Id_16458535
You may need to reload the object before continuing.
```
