### ISSUE TITLE
TypeError on move Image on Python 3.5

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#169]
```
Traceback (most recent call last):
File "/home/omero-web/venv3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/home/omero-web/venv3/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/omero-web/venv3/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/omero-web/venv3/lib/python3.5/site-packages/omeroweb/decorators.py", line 488, in wrapped
retval = f(request, *args, **kwargs)
File "/home/omero-web/venv3/lib/python3.5/site-packages/omeroweb/webclient/views.py", line 914, in api_links
json_data = json.loads(request.body)
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

see:
 - https://forum.image.sc/t/query-for-datasetimagelink-id/37206
 - QAs 29254 and 29255

cc: @dsudar

**Comment by joshmoore** [comment]
@mtbc has confirmed on Python 3.5. Testing on Python 3.6 (merge-ci) I _don't_ see this behavior.
