### ISSUE TITLE
test_web unit tests need templates in dist/etc/templates/web

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#18]
6 test_web.py unit tests are marked as failing in
See https://github.com/ome/omero-web/pull/10/commits/3f297b2dcbc00ff43f77ea6bdc4c50293b16c213

These require templates e.g. ```/omeroweb/templates/nginx.conf.template``` to be in ```dist_dir / "etc" / "templates" / "web"```.

**Comment by manics** [comment]
This is arguably a blocker since it prevents the decoupled OMERO.web from generating nginx templates:
```
$ omero web config nginx
Traceback (most recent call last):
  File "/tmp/omeroweb/bin/omero", line 130, in <module>
    rv = omero.cli.argv()
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/cli.py", line 1706, in argv
    cli.invoke(args[1:])
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/cli.py", line 1159, in invoke
    stop = self.onecmd(line, previous_args)
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/cli.py", line 1236, in onecmd
    self.execute(line, previous_args)
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/cli.py", line 1318, in execute
    args.func(args)
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/install/windows_warning.py", line 26, in wrapper
    return func(self, *args, **kwargs)
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/plugins/web.py", line 82, in wrapper
    return func(self, *args, **kwargs)
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/plugins/web.py", line 115, in wrapper
    return func(self, *args, **kwargs)
  File "/tmp/omeroweb/lib/python2.7/site-packages/omero/plugins/web.py", line 307, in config
    c = file(self._get_web_templates_dir() / template_file).read()
IOError: [Errno 2] No such file or directory: path(u'/tmp/omeroweb/etc/templates/web/nginx.conf.template')
```
