### ISSUE TITLE
AttributeError: 'NoneType' in controller/share.py

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#210]
on ns-web-pub today:

```
Analyze this line2020-08-28 08:59:52,896 ERROR [ omeroweb.webclient.views] (proc.05086) manage_action_containers():2873 Traceback (most recent call last):

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 2871, in manage_action_containers

Analyze this linemanager.removeImage(image_id)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/controller/share.py", line 180, in removeImage

Analyze this lineself.conn.removeImage(self.share.id, image_id)

Analyze this lineAttributeError: 'NoneType' object has no attribute 'id'

Analyze this line
```

**Comment by joshmoore** [comment]
Raised again today on ns-web-pub. cc: @will-moore

**Comment by joshmoore** [comment]
Raised again on ns-web-pub.

**Comment by joshmoore** [comment]
Raised again on ns-web-pub

**Comment by joshmoore** [comment]
Again today on ns-web-pub
