### ISSUE TITLE
webadmin handle lookupLdapAuthExperimenter

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#23]
When loading an Experimenter, for e.g. ```/webadmin/experimenter/edit/id``` this fails if there is an exception when looking up LDAP user, e.g:

https://www.openmicroscopy.org/qa2/qa/feedback/27937/
https://www.openmicroscopy.org/qa2/qa/feedback/27865/
 https://www.openmicroscopy.org/qa2/qa/feedback/27767/
 https://www.openmicroscopy.org/qa2/qa/feedback/18791/
```
Traceback (most recent call last):

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/omero/OMERO.py/lib/python/omeroweb/decorators.py", line 486, in wrapped
retval = f(request, *args, **kwargs)

File "/home/omero/OMERO.py/lib/python/omeroweb/decorators.py", line 536, in wrapper
context = f(request, *args, **kwargs)

File "/home/omero/OMERO.py/lib/python/omeroweb/webadmin/views.py", line 478, in manage_experimenter
prepare_experimenter(conn, eid)

File "/home/omero/OMERO.py/lib/python/omeroweb/webadmin/views.py", line 107, in prepare_experimenter
isLdapUser = experimenter.isLdapUser()

File "/home/omero/OMERO.py/lib/python/omeroweb/webclient/webclient_gateway.py", line 2289, in isLdapUser
self.ldapUser = admin_serv.lookupLdapAuthExperimenter(self.id)

File "/home/omero/OMERO.py/lib/python/omero/gateway/__init__.py", line 4671, in __call__
return self.handle_exception(e, *args, **kwargs)

File "/home/omero/OMERO.py/lib/python/omeroweb/webclient/webclient_gateway.py", line 2109, in handle_exception
e, *args, **kwargs)

File "/home/omero/OMERO.py/lib/python/omero/gateway/__init__.py", line 4668, in __call__
return self.f(*args, **kwargs)

File "/home/omero/OMERO.py/lib/python/omero_api_IAdmin_ice.py", line 1123, in lookupLdapAuthExperimenter
return _M_omero.api.IAdmin._op_lookupLdapAuthExperimenter.invoke(self, ((id, ), _ctx))

ApiUsageException: exception ::omero::ApiUsageException
{
serverStackTrace = ome.conditions.ApiUsageException: Cannot find unique user DistinguishedName: found=0
at ome.logic.LdapImpl.mapUserName(LdapImpl.java:213)
at ome.logic.LdapImpl.findExperimenter(LdapImpl.java:174)
```

**Comment by will-moore** [comment]
Fixed in https://github.com/ome/omero-web/pull/24
