### ISSUE TITLE
Bug: missing None check on /webclient/metadata_acquisition/image/

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#246]
```
2021-01-08 08:05:25,706 ERROR [ django.request] (proc.02796) handle_uncaught_exception():135 HTTP 500 <WSGIRequest: GET '/webclient/metadata_acquisition/image/146114/?_=1610093069073'>
Traceback (most recent call last):
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 596, in wrapper
context = f(request, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 1834, in load_metadata_acquisition
manager.companionFiles()
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/controller/container.py", line 386, in companionFiles
hasattr(ann._obj, "file")
AttributeError: 'NoneType' object has no attribute '_obj'
```

**Comment by will-moore** [comment]
Can't see how that would happen. ```conn.listAnnotations()``` giving a `None` annotation. 
`AnnotationWrapper._wrap()` only returns `None` if `obj.__class__` not in `cls.registry` but all classes are in the registry except maybe `ListAnnotation`: https://docs.openmicroscopy.org/omero-blitz/5.5.8/slice2html/omero/model/ListAnnotation.html ?

**Comment by joshmoore** [comment]
Maybe if `close()` or something was already called?
