### ISSUE TITLE
Bug: NaN leads to ValueError in histogram_json

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#254]
```
2021-02-01 05:24:14,171 ERROR [ django.request] (proc.20332) handle_uncaught_exception():135 Internal Server Error: /webgateway/histogram_json/158599/channel/0/
Traceback (most recent call last):
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webgateway/views.py", line 2755, in histogram_json
theZ = int(request.GET.get("theZ", 0))
ValueError: invalid literal for int() with base 10: 'NaN'
```

**Comment by will-moore** [comment]
Although we *could* handle that exception and just use `theZ = 0`, that's not the approach we've taken elsewhere since it silently provides possibly wrong data.
Tried to understand why the JS code is asking for `?theZ=NaN` but can't reproduce.

**Comment by joshmoore** [comment]
Understood. But is this an error that the sysadmin needs to handle?
