### ISSUE TITLE
Bug: int() argument must be a string (from switch_active_group)

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#259]
```
2021-02-14 10:41:48,924 ERROR [ django.request] (proc.14709) handle_uncaught_exception():135 Internal Server Error: /webclient/active_group/

Analyze this lineTraceback (most recent call last):

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner

Analyze this lineresponse = get_response(request)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response

Analyze this lineresponse = self.process_exception_by_middleware(e, request)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response

Analyze this lineresponse = wrapped_callback(request, *callback_args, **callback_kwargs)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped

Analyze this lineretval = f(request, *args, **kwargs)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 332, in change_active_group

Analyze this lineswitch_active_group(request)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 345, in switch_active_group

Analyze this lineactive_group = int(active_group)

Analyze this lineTypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by joshmoore** [comment]
seen on demo this morning.
