### ISSUE TITLE
Render shape mask - index out of range

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#262]
Seen on demo:

```
Traceback (most recent call last):

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
    retval = f(request, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webgateway/views.py", line 804, in render_shape_mask
    img.putpixel((x, y), fill)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/PIL/Image.py", line 1692, in putpixel
    return self.im.putpixel(xy, value)

IndexError: image index out of range

<WSGIRequest: GET '/webgateway/render_shape_mask/505860/'>
```

**Comment by sbesson** [comment]
Another occurence of this issue was reported yesterday in `ns-web.openmicroscopy.org`

```
2022-05-16 21:24:35,954 ERROR [ django.request] (proc.14403) log_response():230 Internal Server Error: /webgateway/render_shape_mask/4562441/
...
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/PIL/Image.py", line 1692, in putpixel

return self.im.putpixel(xy, value)

IndexError: image index out of range
```
