### ISSUE TITLE
Bug: local variable 'context' referenced before assignment

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-web#292]
This morning on ns-web-pub:

```
Analyze this line2021-05-21 11:35:52,014 ERROR [ django.request] (proc.02840) handle_uncaught_exception():135 Internal Server Error: /webclient/action/add/share/

Analyze this lineTraceback (most recent call last):

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner

Analyze this lineresponse = get_response(request)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response

Analyze this lineresponse = self.process_exception_by_middleware(e, request)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response

Analyze this lineresponse = wrapped_callback(request, *callback_args, **callback_kwargs)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped

Analyze this lineretval = f(request, *args, **kwargs)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 597, in wrapper

Analyze this linecontext = f(request, *args, **kwargs)

Analyze this lineFile "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 3113, in manage_action_containers

Analyze this linecontext["template"] = template

Analyze this lineUnboundLocalError: local variable 'context' referenced before assignment
```

**Comment by will-moore** [comment]
I wonder how the user got that URL: `/webclient/action/add/share/`.
Since the URL regex is `r"^action/(?P<action>[a-zA-Z]+)/(?:(?P<o_type>[a-zA-Z]+)/)?(?:(?P<o_id>[0-9]+)/)?$"`
we don't get the 404 that we would like, now that `add/share` is no-longer supported.
