### ISSUE TITLE
ValidationException: experimenters may not remove themselves from the 'system' or 'user' group

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#364]
Reported at https://www.openmicroscopy.org/qa2/qa/feedback/30912/

When editing 'system' group, it shouldn't be possible to remove yourself from the group:

![Screenshot 2022-03-17 at 08 59 34](https://user-images.githubusercontent.com/900055/158774136-23398bcb-1d66-4c10-aa2a-ca5ba19bdc67.png)

<details>
<summary>Full Exception</summary>

```
Traceback (most recent call last):

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omeroweb/decorators.py", line 597, in wrapper
context = f(request, *args, **kwargs)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omeroweb/webadmin/views.py", line 675, in manage_experimenter
institution,

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 1244, in updateExperimenter
admin_serv.removeGroups(up_exp, rmGroups)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4796, in __call__
return self.handle_exception(e, *args, **kwargs)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 2109, in handle_exception
super(OmeroWebSafeCallWrapper, self).handle_exception(e, *args, **kwargs)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4793, in __call__
return self.f(*args, **kwargs)

File "/home/admin/omerowebvenv/lib64/python3.6/site-packages/omero_api_IAdmin_ice.py", line 2011, in removeGroups
return _M_omero.api.IAdmin._op_removeGroups.invoke(self, ((user, groups), _ctx))

omero.ValidationException: exception ::omero::ValidationException
{
serverStackTrace = ome.conditions.ValidationException: experimenters may not remove themselves from the 'system' or 'user' group
```
</details>

**Comment by will-moore** [comment]
Seen again at https://www.openmicroscopy.org/qa2/qa/feedback/31190/ 

```
Traceback (most recent call last):

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 597, in wrapper
context = f(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webadmin/views.py", line 886, in manage_group
removalFails = conn.setMembersOfGroup(group, new_members)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 1388, in setMembersOfGroup
admin_serv.removeGroups(e._obj, [group._obj])

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4858, in __call__
return self.handle_exception(e, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 2109, in handle_exception
super(OmeroWebSafeCallWrapper, self).handle_exception(e, *args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4855, in __call__
return self.f(*args, **kwargs)

File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_api_IAdmin_ice.py", line 2011, in removeGroups
return _M_omero.api.IAdmin._op_removeGroups.invoke(self, ((user, groups), _ctx))

omero.ValidationException: exception ::omero::ValidationException
{
serverStackTrace = ome.conditions.ValidationException: experimenters may not remove themselves from the 'system' or 'user' group
at ome.logic.AdminImpl.removeGroups(AdminImpl.java:796)
at sun.reflect.GeneratedMethodAccessor2031.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by will-moore** [comment]
Seen again at https://www.openmicroscopy.org/qa2/qa/feedback/42104/

**Comment by will-moore** [comment]
Reported again at https://qa.openmicroscopy.org/qa/feedback/42428/

**Comment by will-moore** [comment]
Reported at https://qa.openmicroscopy.org/qa/feedback/92199/ "Web Bug 5.24.0"
