### ISSUE TITLE
ObjectNotExistException has no attribute message

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#380]
Seen today on nightshade:

webclient/api/containers/?id=8908&experimenter_id=8908&page=0&group=852

```
Traceback (most recent call last):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 696, in api_container_list
    limit=limit,
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/tree.py", line 372, in marshal_projects
    for e in qs.projection(q, params, service_opts):
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 5039, in __getattr__
    obj = self._obj or self._getObj()
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4970, in _getObj
    self._obj = self._create_func()
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero/gateway/__init__.py", line 4946, in cf
    obj = getattr(self._conn.c.sf, self._func_str)()
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omero_API_ice.py", line 758, in getQueryService
    return _M_omero.api.ServiceFactory._op_getQueryService.invoke(self, ((), _ctx))

During handling of the above exception (exception ::Ice::ObjectNotExistException
{
    id =
    {
        name = 2247bd56-de1d-4572-9636-6dac15994dc4
        category = session-c54dbdd5-d9ff-41be-82eb-29dbdd5e7a06
    }
    facet =
    operation = getQueryService
}), another exception occurred:
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
    retval = f(request, *args, **kwargs)
  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 753, in api_container_list
    return HttpResponseServerError(e.message)

Exception Type: AttributeError at /webclient/api/containers/
Exception Value: 'ObjectNotExistException' object has no attribute 'message'
```

**Comment by will-moore** [comment]
Seen again at at different endpoint, on omero.lifesci.dundee.ac.uk

Currently `OMERO.web 5.31.0.`

```
Internal Server Error: /webclient/api/shares/

AttributeError at /webclient/api/shares/
'ObjectNotExistException' object has no attribute 'message'

Request Method: GET

Django Version: 5.2.10
Python Executable: /opt/omero/web/venv-3.12/bin/python3.12
Python Version: 3.12.13
Python Path: ['/opt/omero/web/venv-3.12/lib/python3.12/site-packages/omeroweb', '/opt/omero/web/venv-3.12/bin', '/opt/omero/web/OMERO.web/var/lib', '/usr/lib64/python312.zip', '/usr/lib64/python3.12', '/usr/lib64/python3.12/lib-dynload', '/opt/omero/web/venv-3.12/lib64/python3.12/site-packages', '/opt/omero/web/venv-3.12/lib/python3.12/site-packages', '/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omeroweb', '/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/setuptools/_vendor']
Server time: Thu, 18 Jun 2026 10:15:05 +0100

Traceback (most recent call last):
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omeroweb/webclient/views.py", line 1429, in api_share_list
    discussions = tree.marshal_discussions(

  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omeroweb/webclient/tree.py", line 1858, in marshal_discussions
    for e in qs.projection(q, params, service_opts):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omero/gateway/__init__.py", line 4878, in __call__
    return self.handle_exception(e, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omeroweb/webclient/webclient_gateway.py", line 2098, in handle_exception
    self.proxyObjectWrapper._obj = self.proxyObjectWrapper._create_func()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omero/gateway/__init__.py", line 5028, in cf
    obj = getattr(self._conn.c.sf, self._func_str)()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omero_API_ice.py", line 758, in getQueryService
    return _M_omero.api.ServiceFactory._op_getQueryService.invoke(self, ((), _ctx))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception (exception ::Ice::ObjectNotExistException
{
    id =
    {
        name = 9f159801-5ef1-40a1-8ef9-9a40c4a85db4
        category = session-98b96f15-ae49-4c15-8005-11fad491b138
    }
    facet =
    operation = getQueryService
}), another exception occurred:
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omeroweb/decorators.py", line 538, in wrapped
    retval = f(request, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/omero/web/venv-3.12/lib64/python3.12/site-packages/omeroweb/webclient/views.py", line 1437, in api_share_list
    return HttpResponseServerError(e.message)
                                   ^^^^^^^^^

Exception Type: AttributeError at /webclient/api/shares/
Exception Value: 'ObjectNotExistException' object has no attribute 'message'
Raised during: omeroweb.webclient.views.api_share_list
```
