### ISSUE TITLE
No active group found

### ISSUE THREAD

**Issue by jburel** [ome/omero-web#387]
See https://www.openmicroscopy.org/qa2/qa/feedback/31171/
```
Traceback (most recent call last):
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 597, in wrapper
context = f(request, *args, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 576, in load_template
return _load_template(request=request, menu=menu, conn=conn, url=url, **kwargs)
File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 496, in _load_template
leaders, members = conn.getObject("ExperimenterGroup", active_group).groupSummary()
AttributeError: 'NoneType' object has no attribute 'groupSummary'
```

Code is 
```
active_group = request.session.get("active_group") or conn.getEventContext().groupId
# prepare members of group...
leaders, members = conn.getObject("ExperimenterGroup", active_group).groupSummary()
```

**Comment by dominikl** [comment]
A bunch of QAs with that issue today, e.g. [32190](https://www.openmicroscopy.org/qa2/qa/feedback/32190/), [31814](https://www.openmicroscopy.org/qa2/qa/feedback/31814/), etc. (all from the same IP though).

**Comment by will-moore** [comment]
A ton of spam (or security testing) QAs today with this error: E.g. https://www.openmicroscopy.org/qa2/qa/feedback/33454/
