### ISSUE TITLE
NoneType' object has no attribute 'getEventContext'

### ISSUE THREAD

**Issue by jburel** [ome/omero-web#493]
Using Web Bug 5.22.0
https://www.openmicroscopy.org/qa2/qa/feedback/33717/
```
Traceback (most recent call last):

File "/home/omero-web/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/home/omero-web/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/decorators.py", line 597, in wrapper
context = f(request, *args, **kwargs)

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/webclient/views.py", line 577, in load_template
return _load_template(request=request, menu=menu, conn=conn, url=url, **kwargs)

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/webclient/views.py", line 495, in _load_template
active_group = request.session.get("active_group") or conn.getEventContext().groupId

AttributeError: 'NoneType' object has no attribute 'getEventContext'
```

**Comment by jburel** [comment]
cc @will-moore @knabar

**Comment by sbesson** [comment]
Is that also solved by https://github.com/ome/omero-web/pull/492 ? Looks like we keep duplicating this stack trace.

**Comment by jburel** [comment]
Duplicate see #383
