### ISSUE TITLE
createDataset in All Members 

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#500]
In "All Members" view of a group, the option to create a Dataset under another's Project is not disabled...

From https://www.openmicroscopy.org/qa2/qa/feedback/33803/
"I tried to create a new "Data Set" (by clicking the green folder icon in Omero.Web,under the "Explore" tab)
in an other members (an "All Members"-Project, icon is a grey-blue folder): Entered Name and Description (pruely ASCII-Letters of the latin alphabet, nothing fancy :), clicked "OK" and landed here: "Server Error. (500)".

```
Traceback (most recent call last):

File "/opt/omero/web/venv3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omeroweb/decorators.py", line 597, in wrapper
context = f(request, *args, **kwargs)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omeroweb/webclient/views.py", line 2882, in manage_action_containers
oid = manager.createDataset(name, description, owner=owner)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omeroweb/webclient/controller/container.py", line 581, in createDataset
self.conn.saveAndReturnId(l_ds, owner=owner)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 1681, in saveAndReturnId
res = u.saveAndReturnObject(obj, ctx)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omero/gateway/__init__.py", line 4859, in __call__
return self.handle_exception(e, *args, **kwargs)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omeroweb/webclient/webclient_gateway.py", line 2123, in handle_exception
super(OmeroWebSafeCallWrapper, self).handle_exception(e, *args, **kwargs)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omero/gateway/__init__.py", line 4856, in __call__
return self.f(*args, **kwargs)

File "/opt/omero/web/venv3/lib/python3.6/site-packages/omero_api_IUpdate_ice.py", line 163, in saveAndReturnObject
return _M_omero.api.IUpdate._op_saveAndReturnObject.invoke(self, ((obj, ), _ctx))

omero.SecurityViolation: exception ::omero::SecurityViolation
{
serverStackTrace = ome.conditions.SecurityViolation: Group is rwra--. Cannot link to object: ome.model.containers.Project:Id_2
```

**Comment by will-moore** [comment]
Same error seen at https://qa.openmicroscopy.org/qa/feedback/42471/

`Web Bug 5.19.0`

```
< DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
Traceback (most recent call last):

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omeroweb/decorators.py", line 538, in wrapped
retval = f(request, *args, **kwargs)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omeroweb/decorators.py", line 597, in wrapper
context = f(request, *args, **kwargs)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omeroweb/webclient/views.py", line 2878, in manage_action_containers
oid = manager.createDataset(name, description, owner=owner)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omeroweb/webclient/controller/container.py", line 581, in createDataset
self.conn.saveAndReturnId(l_ds, owner=owner)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omeroweb/webclient/webclient_gateway.py", line 1667, in saveAndReturnId
res = u.saveAndReturnObject(obj, ctx)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omero/gateway/__init__.py", line 4859, in __call__
return self.handle_exception(e, *args, **kwargs)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omeroweb/webclient/webclient_gateway.py", line 2109, in handle_exception
super(OmeroWebSafeCallWrapper, self).handle_exception(e, *args, **kwargs)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omero/gateway/__init__.py", line 4856, in __call__
return self.f(*args, **kwargs)

File "/home/ubuntu/prog/omero/venv_server/lib/python3.8/site-packages/omero_api_IUpdate_ice.py", line 163, in saveAndReturnObject
return _M_omero.api.IUpdate._op_saveAndReturnObject.invoke(self, ((obj, ), _ctx))

omero.SecurityViolation: exception ::omero::SecurityViolation
{
serverStackTrace = ome.conditions.SecurityViolation: Group is rwra--. Cannot link to object: ome.model.containers.Project:Id_1
```

**Comment by will-moore** [comment]
Again at https://qa.openmicroscopy.org/qa/feedback/91864/ 
https://qa.openmicroscopy.org/qa/feedback/91865/
