### ISSUE TITLE
load_server_settings() fails to open config

### ISSUE THREAD

**Issue by mtbc** [ome/omero-web#75]
Servers like `ns-web` log plenty of errors like,
```
2019-11-15 10:05:21,320 ERROR [                     omeroweb.decorators] (proc.21412) load_server_settings():264 Traceback (most recent call last):
  File "/opt/omero/web/OMERO.web/lib/python/omeroweb/decorators.py", line 261, in load_server_settings
    propertiesToDict(conn.getClientSettings(),
  File "/opt/omero/web/OMERO.web/lib/python/omeroweb/webclient/webclient_gateway.py", line 250, in getClientSettings
    localcfg = AdminControl().open_config()
  File "/opt/omero/web/OMERO.web/lib/python/omero/plugins/admin.py", line 1686, in open_config
    self.ctx.die(577, str(e))
  File "/opt/omero/web/OMERO.web/lib/python/omero/cli.py", line 592, in die
    raise Exception((rc, args))
Exception: (577, "(1, 'Resource temporarily unavailable')")
```

**Comment by mtbc** [comment]
@sbesson recalls that the problem may be related to concurrent access to the locked `config.xml` client-side.
